name: Direct Imaging Solutions
favicon: null
layout_spectrum: 0.54019
typography_spectrum: 0.54173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f3f3f'
    - '#f04b45'
    - '#b8b8b8'
    - '#888888'
  brandStrength: 0.6097404018510133
  lightness: 0.6810464996378869
  saturation: 0.4375
  rhythmicContrast: 0.1410225173458457
purpose: []
